### ISSUE TITLE
Can Write Description Please

### ISSUE THREAD

**Issue by heroturker** [cyio/vagrant#1]
What it is ? Your Development Environment ?

Because I m also looking for nodejs/ javascript development environment with vagrant..

**Comment by cyio** [comment]
I have tried  to find same things when I was using Windows a few months ago. But then I switch to Linux for better development experience.

There may isn't  exist an out-of-the-box solution for Node&JS with vagrant for now. 

You could build your environment based this project:  [drmyersii/vagrant-env-basher: Reusable Bash provisioning scripts for Vagrant (or Ubuntu 14.04) environments.](https://github.com/drmyersii/vagrant-env-basher)
